### PR TITLE
closes #723

### LINKED ISSUE #723: Remove the konig-core dependency from konig-data-app-common module
The `konig-data-app-common` module is a runtime module; it contains code that runs in production.

By contrast, `konig-core` is used primarily for code generation.  It is not intended for use in a production setting. (There may be special cases where it is appropriate to use in production, but such cases are rare.)

Currently, `konig-data-app-common` depends on `konig-core` because it uses `io.konig.core.KonigException`.

I want to remove the dependency of `konig-core` from the `konig-data-app-common` module by introducing a different Exception type instead of io.konig.core.KonigException

### PR DESCRIPTION
**Pull request by DamodarAllareddy**

### CODE REVIEW

File: konig-data-app-generator/src/main/java/io/konig/data/app/generator/DataAppGenerator.java [hunk 1]
```diff
@@ -75,7 +76,12 @@ private void handlePath(BasicDataApp app, Path path) throws DataAppGeneratorExce
 				container.setDefaultShape((URI)defaultShape.getId());
 				container.setExtentClass(extentClass);
 				container.setSlug(slug);
-				app.addContainer(container);
+				try {
+					app.addContainer(container);
+				} catch (DataAppException e) {
+					// TODO Auto-generated catch block
```
Comment (gmcfall) [inline konig-data-app-generator/src/main/java/io/konig/data/app/generator/DataAppGenerator.java]: Please remove the TODO comment
