### PR TITLE
closes #757

### LINKED ISSUE #757: To eliminiate the risk of cross site scripting attacks
This issue is about dealing with prevention of script injection and sql injection that may occur through the API request.
String escape utils and other data validation have been added for the query string to prevent this case, but since our data deals with url and url some of the characters such as (/ when added a escape sequence results in a big query exception). So in order to fix this as a temporary solution we have decided that we shall not allow some of the special characters (such as <>() and so) and some keywords such as (select,script,insert,update,delete,alert,html,from,into) in those fields where string escape utils will not help.

### PR DESCRIPTION
**Pull request by ElakiyaUdhayanan**

### CODE REVIEW

File: konig-data-app-common/src/main/java/io/konig/data/app/common/ExtentContainer.java [hunk 1]
```diff
@@ -209,6 +217,43 @@ public boolean validateQueryParam(String key, String value, URI datatype ) throw
...
-	}
-
-}
+	}
+	
+	 boolean validateValue (String value )throws DataAppException{
+		 String  errorMsg = MessageFormat.format("IllegalArgumentException : Invalid  value : {0}",
+				 value);
+		  Pattern special = Pattern.compile ("[!@#$%&*()+=|<>?{}\\[\\]~]");
+		  Matcher hasSpecial = special.matcher(value);
```
Comment (gmcfall) [inline konig-data-app-common/src/main/java/io/konig/data/app/common/ExtentContainer.java]: You should set...

```
   value = value.toUpperCase();
```

and then check only for the upper case versions of the keywords.

File: konig-data-app-common/src/main/java/io/konig/data/app/common/ExtentContainer.java [hunk 2]
```diff
@@ -209,9 +209,9 @@ public boolean validateQueryParam(String key, String value, URI datatype ) throw
 				Long.parseLong(value);
 				return true;
 			}
-			throw new DataAppException(errorMsg);
```
Comment (gmcfall) [inline konig-data-app-common/src/main/java/io/konig/data/app/common/ExtentContainer.java]: You should delete the `errorMsg` variable since you are no longer using it.  (There are two instances of this variable that are never used.)
